# Generated by Django 5.1.5 on 2025-01-19 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TelegramUser',
                'verbose_name_plural': 'TelegramUsers',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_admin.telegramuser'),
        ),
    ]
