# Generated by Django 5.1.5 on 2025-01-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_telegramuser_remove_customuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('api_hash', models.CharField(max_length=128)),
                ('api_id', models.CharField(max_length=54)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TelegramAccount',
                'verbose_name_plural': 'TelegramAccounts',
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'TelegramChannel',
                'verbose_name_plural': 'TelegramChannels',
            },
        ),
    ]
