# Generated by Django 5.1.5 on 2025-01-19 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_telegramaccount_telegramchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='telegram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_admin.telegramaccount'),
        ),
    ]
