# Generated by Django 5.1.5 on 2025-01-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_telegramchannel_telegram_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('images', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'TelegramChannel',
                'verbose_name_plural': 'TelegramChannels',
            },
        ),
    ]
