# Generated by Django 5.1.5 on 2025-01-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='channel_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
