# Generated by Django 5.1.5 on 2025-01-24 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0007_telegramchannel_last_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='telegram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_admin.telegramaccount'),
        ),
    ]
